<a href="https://colab.research.google.com/github/sagarrodge12/learningMachineLearning/blob/main/ML_DAY_4%20(1)%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.array(100)
arr2= np.array([1,2,3,4,5])
arr3 = np.array([[1,2,"NTT"],[4,5,6]])
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [ ]:
arr5 = np.array([1,2,3,4,5], ndmin=6)
print(arr5)
print('number of dimensions :', arr5.ndim)

[[[[[[1 2 3 4 5]]]]]]
number of dimensions : 6


In [ ]:
arr2= np.array([1,2,3,4,5])
print(arr2[::-1])

[5 4 3 2 1]


In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3[-1,-1])

6


In [ ]:
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4[0,1,2])

6


In [ ]:
arr2= np.array([1,2,3,4,5])
l=arr2[1:4]
print(l)
l2= list(l)
print(type(l2))
print(type(l))

[2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
arr2= np.array([1,2,3,4,5])
print([arr2[-3:-1]])

[array([3, 4])]


In [ ]:
arr3 = np.array([[1,2,3,8,9,10],[4,5,6,9,9,9]])
print(arr3[1:4,1:3])

[[5 6]]


In [ ]:
arr2= np.array([1,2,3,4,1.1])
print(arr2.dtype)
print(arr2[0]+arr2[1])

float64
3.0


In [ ]:
arr2= np.array([1,2,3,4,"NTT"])
print(arr2.dtype)
print(arr2[0]+arr2[1])

<U21
12


In [ ]:
a="ntt"
b="blr"
print(a+b)

nttblr


In [ ]:
arr2= np.array([1.1,2.0,3.0,4.0,5])
print(arr2.dtype)


float64


In [ ]:
arr = np.array([1,2,3,4],dtype="S")
print(arr)
print(arr[0]+arr[1])
print(arr.dtype)

[b'1' b'2' b'3' b'4']
b'12'
|S1


In [ ]:
arr = np.array([1,2,3,4],dtype="i8")
print(arr)
print(arr[0]+arr[1])
print(arr.dtype)

[1 2 3 4]
3
int64


In [ ]:
arr2= np.array([1.1,0,3.0,4.0,0])
na = arr2.astype(bool)
print(na)
print(na.dtype)
print(arr2.dtype)

[ True False  True  True False]
bool
float64


In [ ]:
#copy Vs View

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#Numpy Array Shape

arr3 = np.array([[1,2,3,8,9,10],[4,5,6,9,9,9]])
print(arr3.shape)


(2, 6)


In [ ]:
arr = np.array([[[1,2,3,4],[8,9,10,11]],[[1,2,3,4],[8,9,10,11]]],ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[ 1  2  3  4]
    [ 8  9 10 11]]

   [[ 1  2  3  4]
    [ 8  9 10 11]]]]]
shape of array : (1, 1, 2, 2, 4)


In [ ]:
#reshaping

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,12])
newarr = arr.reshape(2,3,2)
print(newarr)


ValueError: cannot reshape array of size 13 into shape (2,3,2)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
na = arr.reshape(2,3,-1)
print(na)
print(na.shape)

ValueError: cannot reshape array of size 9 into shape (2,3,newaxis)

In [ ]:
#print(na)
nna = na.reshape(-1)
print(nna)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [1]:
import numpy as np

arr1 = np.array(100)
arr2 = np.array([1,2,3,4])
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr1.ndim)  #ndim returns dimentions if array
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [2]:
# alternate way of creating multi dimentional array

arr5 = np.array([1,2,3,4,5], ndmin=6) # whatever element you give it'll create that dim array
print(arr5)
print('number of dimensions :', arr5.ndim)

[[[[[[1 2 3 4 5]]]]]]
number of dimensions : 6


In [7]:
# How to access the array

arr2= np.array([1,2,3,4,5])
print(arr2[0])
print(arr2[0:2]) # can usee the range as well
print(arr2[-1])
print(arr2[-3:-1]) # -1 element is 5 since end elemt won't be included it won't print
print(arr2[0::2]) # step size is 2 i.e. 2-1 =1 will skip one value

1
[1 2]
5
[3 4]
[1 3 5]


In [9]:
# How to access double dim array

arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3[0,1]) # in python we have one single square bracket 0th row 1st col
print(arr3[1,2]) # 1st row 2nd col
print(arr3[1,-1]) # 1st row last col

# in terms of row positive indexing starts from left to right & negative indexing right to left
# in terms of col positive indexing starts from top to bottom & negative indexing bottom to top

2
6


In [10]:
# access three dim array

arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4[0,1,2]) # 0th array 1st row 2nd col

6


In [12]:
# Slicing -  from the given array how do we extract the part of array that is slicing is
# syntax - [start : end : step]

arr2 = np.array([1,2,3,4])
l = arr2[1:4] # slicing
print(l)
l2 = list(l)
print(type(l2))  # if you apply slicing on list type will be list
print(type(l)) # if you apply slicing on array type will be array

[2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [13]:
arr2 = np.array([1,2,3,4,5])
print([arr2[-3:-1]]) # why it is traversing from left to right because we have give step size positive (default)


[array([3, 4])]


In [14]:
arr3 = np.array([[1,2,3,8,9,10],[4,5,6,9,9,9]]) # 2x 6 dim array
print(arr3[1,1:2]) #1st row, starting from 1 end is 2 and it is excluded wo it'll print 5

print(arr3[1:4,1:3]) #it'll take a subset of given array i.e first arg is for row
                     #1:4 means it'll consider 1st 2nd 3rd rows, since we dont have 2nd and 3rd it won't consider those and it won't throw error cause we know if you give wrong indexing in range it won't throw error
                     #1:3 means it'll consider 1st and 2nd cols
                     #intersection will comes out

[5]
[[5 6]]


In [ ]:
# Data types in python by default - string, Integer, float, boolean, complex
# since array is homogenious we are going to bother about this
# NumPy has some extra data types and data types numPy uses diff character to represent them
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunck of memory for other type (void)


In [18]:
arr2 = np.array([1,2,3,4,1.1])
print(arr2.dtype) # if you add one float ele whole array will become float type because array will take highest data type only and float is hightest
print(arr2[0]+arr2[1])

float64
3.0


In [19]:
arr2 = np.array([1,2,3,4,"NTT"])
print(arr2.dtype) # whole array become string type
print(arr2[0]+arr2[1]) # concatination will happen sinceits string

<U21
12
