In [4]:
import numpy as np

arr1 = np.array(100)
arr2= np.array([1,2,3,4,5])
arr3 = np.array([[1,2,"NTT"],[4,5,6]])
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [3]:
arr5 = np.array([1,2,3,4,5], ndmin=6)
print(arr5)
print('number of dimensions :', arr5.ndim)

[[[[[[1 2 3 4 5]]]]]]
number of dimensions : 6


In [8]:
arr2= np.array([1,2,3,4,5])
print(arr2[::-1])

[5 4 3 2 1]


In [12]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3[-1,-1])

6


In [13]:
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr4[0,1,2])

6


In [17]:
arr2= np.array([1,2,3,4,5])
l=arr2[1:4]
print(l)
l2= list(l)
print(type(l2))
print(type(l))

[2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [18]:
arr2= np.array([1,2,3,4,5])
print([arr2[-3:-1]])

[array([3, 4])]


In [21]:
arr3 = np.array([[1,2,3,8,9,10],[4,5,6,9,9,9]])
print(arr3[1:4,1:3])

[[5 6]]


In [25]:
arr2= np.array([1,2,3,4,1.1])
print(arr2.dtype)
print(arr2[0]+arr2[1])

float64
3.0


In [26]:
arr2= np.array([1,2,3,4,"NTT"])
print(arr2.dtype)
print(arr2[0]+arr2[1])

<U21
12


In [27]:
a="ntt"
b="blr"
print(a+b)

nttblr


In [28]:
arr2= np.array([1.1,2.0,3.0,4.0,5])
print(arr2.dtype)


float64


In [30]:
arr = np.array([1,2,3,4],dtype="S")
print(arr)
print(arr[0]+arr[1])
print(arr.dtype)

[b'1' b'2' b'3' b'4']
b'12'
|S1


In [32]:
arr = np.array([1,2,3,4],dtype="i8")
print(arr)
print(arr[0]+arr[1])
print(arr.dtype)

[1 2 3 4]
3
int64


In [36]:
arr2= np.array([1.1,0,3.0,4.0,0])
na = arr2.astype(bool)
print(na)
print(na.dtype)
print(arr2.dtype)

[ True False  True  True False]
bool
float64


In [37]:
#copy Vs View

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [38]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [39]:
#Numpy Array Shape

arr3 = np.array([[1,2,3,8,9,10],[4,5,6,9,9,9]])
print(arr3.shape)


(2, 6)


In [42]:
arr = np.array([[[1,2,3,4],[8,9,10,11]],[[1,2,3,4],[8,9,10,11]]],ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[ 1  2  3  4]
    [ 8  9 10 11]]

   [[ 1  2  3  4]
    [ 8  9 10 11]]]]]
shape of array : (1, 1, 2, 2, 4)


In [43]:
#reshaping

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,12])
newarr = arr.reshape(2,3,2)
print(newarr)


ValueError: cannot reshape array of size 13 into shape (2,3,2)

In [55]:
arr = np.array([1,2,3,4,5,6,7,8,9])
na = arr.reshape(2,3,-1)
print(na)
print(na.shape)

ValueError: cannot reshape array of size 9 into shape (2,3,newaxis)

In [56]:
#print(na)
nna = na.reshape(-1)
print(nna)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
