<a href="https://colab.research.google.com/github/sagarrodge12/learningMachineLearning/blob/main/ML_DAY_2%263.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Creating a Tuple
# tuple is hetrogenious can store any type of value like List
# tuple is immutable you cannot change it once you've created it

tup1 = ('physics', 'chemistry', 1997, 2000)
tup2 = (1, 2, 3, 4, 5 )
tup3 = "a", "b", "c", "d"
print(tup1,tup2,tup3)

('physics', 'chemistry', 1997, 2000) (1, 2, 3, 4, 5) ('a', 'b', 'c', 'd')


In [6]:
# creating tuple with the help of constructor tuple

t2 = tuple(tup1)
print(t2)
t3 = tuple(("ntt",1,2,3,4))
print(t3)

# If you pass the list in tuple it'll convert into tuple
t4 = tuple(["ntt",1,2,3,"Hanover"])
print(t4)

('physics', 'chemistry', 1997, 2000)
('ntt', 1, 2, 3, 4)
('ntt', 1, 2, 3, 'Hanover')


In [12]:
t5 = tuple(("SAGAR")) # because it an iterbale element; incase of int it won't work
print(t5)
t6 = tuple(["SAGAR"]) # it'll print SAGAR whole name because you're passing as list
print(t6)
#t7 = tuple((15)) # it'll throw error beause it is not iterable element it won't be able to seperate 1 and 5
t8 = tuple ((15,)) # if you put , it'll understand it is tuple
print(t8)

('S', 'A', 'G', 'A', 'R')
('SAGAR',)
(15,)


In [15]:
a = (20) # this is normal declearation
print(type(a))
b = (20,)  # by using , you can say that its tuple thats why it is introduced cause ambugitivity
print(type(b))


<class 'int'>
<class 'tuple'>


In [18]:
# accessing the tuple
tup3 = (10, "b", 70, "d")
print(tup3[0])  # always use the [] to access
print(tup3[-1])
print(tup3[2])
print(tup3[3])
print(tup3[2:10])

10
d
70
d
(70, 'd')


In [19]:
if "b" in tup3:
    print("yes")
else:
    print("no")

yes


In [20]:
# update a tuple
tup3[0] = 100  #it'll throw error since its immutiable

TypeError: 'tuple' object does not support item assignment

In [23]:
# converting tuple into list
t8 = (1,2,3,4,5)
t9 = list(t8)
print(t9)
print(type(t9))
t9[0] = 100
print(t9)
t8 = tuple(t9)
print(t8)
print(type(t8))

[1, 2, 3, 4, 5]
<class 'list'>
[100, 2, 3, 4, 5]
(100, 2, 3, 4, 5)
<class 'tuple'>


In [24]:
del t8 # deleting tuple whole

In [26]:
#iterate
tup3 = (10,20, 70,60)
for i in tup3:
    print(i)

#iterate without creating tuple
for i in (1,2,3,4):
    print(i)

10
20
70
60
1
2
3
4


In [28]:
s = [["akash",25,"BE"],["John",26,"BSC"],["smith",21,"MBBS"]]
print(s[0])

['akash', 25, 'BE']


In [31]:
d1 = {"name":"akash","age":25,"course":"BE"}
print(d1["name"])

d2 = {10:111, 20:222, 30:333}
print(d2[10])

akash
111


In [36]:
d3 = {"usn1":["akash",25,"BE"], "usn2":["John",26,"BSC"], "usn3":["smith",21,"MBBS"]}
print(d3["usn1"])

print(len(d3))
print(type(d3))

['akash', 25, 'BE']
3
<class 'dict'>


In [38]:
# creating dictonary with the help of constructor dict method
d4 = dict(name = "akash", age = 25, course = "BE")
print(d4)

{'name': 'akash', 'age': 25, 'course': 'BE'}


In [39]:
# i want to check all the keys
x = d4.keys()
print(x)

dict_keys(['name', 'age', 'course'])


In [40]:
# i want to check all the values

y = d4.values()
print(y)

dict_values(['akash', 25, 'BE'])


In [41]:
# i want both keys and values

z = d4.items()
print(z)

dict_items([('name', 'akash'), ('age', 25), ('course', 'BE')])


In [42]:
# update the value
d4["age"] = 26
print(d4)

{'name': 'akash', 'age': 26, 'course': 'BE'}


In [ ]:
# update the values using update method
d4.update({"age":27})
print(d4)

In [43]:
# adding the pair
d4["country"] = "India"
print(d4)

{'name': 'akash', 'age': 26, 'course': 'BE', 'country': 'India'}


In [44]:
# deleting the item
del d4["country"]
print(d4)

{'name': 'akash', 'age': 26, 'course': 'BE'}


In [45]:
# deleting the item using pop
d4.pop("age")
print(d4)

{'name': 'akash', 'course': 'BE'}


In [46]:
# completly deleting dict
del d4

In [49]:
# iterating over d4
d4 = dict(name = "akash", age = 25, course = "BE")
for i in d4:
    print(d4[i])  # only i will access keys and d4[i] will access keys

akash
25
BE


In [54]:
#NUMPY
import numpy as np     # np is alias name for numpy

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)   # print dimension of array
print(arr.size)   # print size of array
print(arr.shape)  # print the shape of array always entered as tuple
print(arr.dtype) # print the data type of array i.e int64

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
5
(5,)
int64


In [56]:
# multidimentional array
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(type(arr1))
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)  #(2,3) 2dimentional array with three column
print(arr1.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
6
(2, 3)
int64


In [57]:
# three dimentaional array

arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)  #(2,2,3) two two dimentional array with three column
print(arr2.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
12
(2, 2, 3)
int64
